---
- name: Désinstaller Elastic Agent via dnf des serveurs cibles
  hosts: all
  tasks:
    - name: desinstaller elk agents
      ansible.builtin.dnf: 
        name: elastic-agent
        state: absent
  
