---
- name: Installer Elastic Agent sur les serveurs cibles
  hosts: all
  tasks:
    #- name: Télécharger Elastic Agent
     # get_url:
     #  url: "https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-9.0.3-linux-x86_64.tar.gz"
     #  dest: "/tmp/elastic-agent-9.0.3-linux-x86_64.tar.gz"
     #  mode: '0644'

    #- name: Extraire Elastic Agent
    #  ansible.builtin.unarchive:
    #    src: "/tmp/elastic-agent-9.0.3-linux-x86_64.tar.gz"
    #    dest: "/tmp/"
    #    remote_src: yes

    - name: Installer Elastic Agent
      ansible.builtin.command:
        cmd: "./elastic-agent install --url=https://fleet02.heritage.africa:8220 --enrollment-token=VFpwUzlaY0I3LW1Sc2lReDJOZXM6MVBfd1l0SXh4OTlaZDN0dklQU09mdw== --insecure"
        chdir: "/tmp/elastic-agent-9.0.3-linux-x86_64"
      args:
        stdin: "yes"
