---
- name: Désinstaller Elastic Agent des serveurs cibles
  hosts: all
  tasks:
    - name: Vérifier si Elastic Agent est installé
      ansible.builtin.command: "elastic-agent status"
      register: agent_status
      ignore_errors: yes
      changed_when: false

    - name: Désinstaller Elastic Agent
      ansible.builtin.command: "/usr/bin/elastic-agent uninstall --force"
      when: agent_status.rc == 0

    - name: Supprimer le répertoire Elastic Agent
      ansible.builtin.file:
        path: "/opt/Elastic/Agent"
        state: absent

    - name: Supprimer l'archive téléchargée
      ansible.builtin.file:
        path: "/tmp/elastic-agent-8.16.4-linux-x86_64.tar.gz"
        state: absent

    - name: Supprimer le dossier extrait
      ansible.builtin.file:
        path: "/tmp/elastic-agent-8.16.4-linux-x86_64"
        state: absent
